### ISSUE TITLE
Bug : 11번 게시글 댓글 안 불러와짐

### ISSUE THREAD

**Issue by minkyu97** [wafflestudio19-5/team5-server#69]
GET https://waffle-minkyu.shop/post/11/comment/
하면 comment serializer에서 userpost_set.get(post=comment.post) 가 2개 이상 불러와진다는 에러 발생

![image](https://user-images.githubusercontent.com/71511067/149001748-1bb6dea3-df33-492e-b7b4-7b7741e14293.png)

![image](https://user-images.githubusercontent.com/71511067/149001687-2ac86d6b-0846-4799-8974-d4e2c59987f2.png)

**Comment by minkyu97** [comment]
익명 이름 붙일 때 생기는 이슈 같은데 회의 때 같이 얘기해보자

**Comment by tjdqhrdkdl** [comment]
수정했어! 이게 모델을 바꿔가지고 기존에 있던 데이터에 직접 userpost를 만들어줬는데 실수로 여러개 만들어서 오류 난 것 같당.. 미안!
